modLoader = "javafml"
loaderVersion = "[44,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "ctrlqr"
version = "${version}"
displayName = "${name}"
displayURL = "${sources}"
authors = "${author}"
description = '''
${description}
'''
logoFile = "icon.png"

[[dependencies.ctrlqr]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.ctrlqr]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,)"
ordering = "NONE"
side = "CLIENT"
