modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "ctrlqr"
version = "${version}"
displayName = "${name}"
displayURL = "${sources}"
authors = "${author}"
description = '''
${description}
'''
logoFile = "icon.png"

[[dependencies.ctrlqr]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.ctrlqr]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19.2]"
ordering = "NONE"
side = "CLIENT"
