name: Release

on: [ workflow_dispatch ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: Make Gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build JARs
        run: ./gradlew build --stacktrace
        env:
          BRANCH_NAME: ${{ github.ref }}

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./build/libs/*.jar  # Adjust the path to your JAR files
          name: Release ${{ github.ref }}
          tag_name: ${{ github.ref | replace('refs/heads/', '') | replace('refs/tags/', '') }}
          draft: false
          prerelease: false

      - name: Set release ID
        run: echo "::set-output name=release_id::${{ steps.create_release.outputs.id }}"
