name: Release

on: [ workflow_dispatch ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: Make Gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build & Upload
        run: ./gradlew build fabric:publishUnified forge:publishUnified quilt:publishUnified --stacktrace
        env:
          curseforge_token: ${{ secrets.CURSEFORGE_TOKEN }}
          modrinth_token: ${{ secrets.MODRINTH_TOKEN }}
          BRANCH_NAME: ${{ github.ref }}
